"""Core ATP: config, exceptions, settings, logging, telemetry, metrics."""

from atp.core.logging import (
    bind_context,
    configure_logging,
    configure_logging_from_settings,
    correlation_context,
    generate_correlation_id,
    get_correlation_id,
    get_logger,
    get_module_log_level,
    reset_logging,
    set_correlation_id,
    set_module_log_level,
)
from atp.core.metrics import (
    ATPMetrics,
    MetricsSettings,
    configure_metrics,
    generate_metrics,
    get_metrics,
    get_metrics_settings,
    get_registry,
    record_adapter_duration,
    record_adapter_error,
    record_evaluator_duration,
    record_llm_call,
    record_test_execution,
    reset_metrics,
)
from atp.core.settings import (
    ATPSettings,
    DashboardSettings,
    LLMSettings,
    LoggingSettings,
    RunnerSettings,
    generate_example_config,
    generate_json_schema,
    get_cached_settings,
    get_settings,
)
from atp.core.telemetry import (
    TelemetrySettings,
    add_exporter_to_provider,
    add_span_event,
    configure_telemetry,
    create_adapter_span,
    create_evaluator_span,
    create_test_span,
    ensure_debug_exporter,
    extract_trace_context,
    get_current_span,
    get_debug_exporter,
    get_telemetry_settings,
    get_tracer,
    inject_trace_context,
    record_exception,
    reset_telemetry,
    set_adapter_response_attributes,
    set_evaluator_result_attributes,
    set_span_attribute,
    set_span_attributes,
    set_test_result_attributes,
    span,
)

__all__ = [
    # Settings
    "ATPSettings",
    "DashboardSettings",
    "LLMSettings",
    "LoggingSettings",
    "RunnerSettings",
    "generate_example_config",
    "generate_json_schema",
    "get_cached_settings",
    "get_settings",
    # Logging
    "bind_context",
    "configure_logging",
    "configure_logging_from_settings",
    "correlation_context",
    "generate_correlation_id",
    "get_correlation_id",
    "get_logger",
    "get_module_log_level",
    "reset_logging",
    "set_correlation_id",
    "set_module_log_level",
    # Telemetry
    "TelemetrySettings",
    "add_exporter_to_provider",
    "add_span_event",
    "configure_telemetry",
    "create_adapter_span",
    "create_evaluator_span",
    "create_test_span",
    "ensure_debug_exporter",
    "extract_trace_context",
    "get_current_span",
    "get_debug_exporter",
    "get_telemetry_settings",
    "get_tracer",
    "inject_trace_context",
    "record_exception",
    "reset_telemetry",
    "set_adapter_response_attributes",
    "set_evaluator_result_attributes",
    "set_span_attribute",
    "set_span_attributes",
    "set_test_result_attributes",
    "span",
    # Metrics
    "ATPMetrics",
    "MetricsSettings",
    "configure_metrics",
    "generate_metrics",
    "get_metrics",
    "get_metrics_settings",
    "get_registry",
    "record_adapter_duration",
    "record_adapter_error",
    "record_evaluator_duration",
    "record_llm_call",
    "record_test_execution",
    "reset_metrics",
]
