"""CLI quickstart command for generating a minimal ATP test project."""

import sys
from pathlib import Path

import click

# Exit codes
EXIT_SUCCESS = 0
EXIT_ERROR = 2

MINIMAL_SUITE_TEMPLATE = """\
# ATP Quick-Start Test Suite
# Generated by: atp quickstart
#
# Edit this file to describe your agent and tests, then run:
#   atp test atp-suite.yaml --adapter={adapter}

name: quickstart-suite
description: Minimal ATP test suite
version: "1.0"

defaults:
  runs_per_test: 1
  timeout_seconds: 60

tests:
  - id: test-001
    name: Hello World
    description: >-
      Ask the agent a simple question to verify the integration works.
    task: "Say hello and confirm you are ready."
    tags:
      - smoke
      - quickstart
"""


@click.command(name="quickstart")
@click.option(
    "--dir",
    "target_dir",
    type=click.Path(path_type=Path),
    default=Path("."),
    show_default=True,
    help="Directory to create the test project in.",
)
@click.option(
    "--adapter",
    type=click.Choice(["http", "cli", "container"]),
    default="http",
    show_default=True,
    help="Agent adapter type to use in the generated suite.",
)
@click.option(
    "--no-run",
    "no_run",
    is_flag=True,
    default=False,
    help="Skip running the suite after creation.",
)
def quickstart_command(target_dir: Path, adapter: str, no_run: bool) -> None:
    """Generate a minimal ATP test project in one command.

    Creates an ``atp-suite.yaml`` file in the target directory with a
    sample test, ready to run with ``atp test``.

    Examples:

      # Create in the current directory and show run instructions
      atp quickstart

      # Create in a specific directory, http adapter
      atp quickstart --dir ./my-agent-tests --adapter http

      # Create without running
      atp quickstart --no-run

    Exit Codes:

      0 - Project created successfully
      2 - Error occurred
    """
    try:
        target_dir = target_dir.resolve()
        target_dir.mkdir(parents=True, exist_ok=True)

        suite_path = target_dir / "atp-suite.yaml"
        suite_path.write_text(MINIMAL_SUITE_TEMPLATE.format(adapter=adapter))

        click.echo(f"Created: {suite_path}")
        click.echo("")
        click.echo("Next steps:")
        click.echo(f"  1. Edit {suite_path} to describe your agent and tests.")
        click.echo(f"  2. Run:  atp test {suite_path} --adapter={adapter}")

        if not no_run:
            click.echo("")
            click.echo(
                "Tip: re-run with --no-run to skip this message and just "
                "create the file."
            )

        sys.exit(EXIT_SUCCESS)

    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(EXIT_ERROR)
