"""add tournament tables

Revision ID: 4e902371a941
Revises: 97e900e385ae
Create Date: 2026-04-02 17:54:18.941188

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e902371a941"
down_revision: str | Sequence[str] | None = "97e900e385ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournaments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("game_type", sa.String(length=100), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=True),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tournaments", schema=None) as batch_op:
        batch_op.create_index("idx_tournaments_status", ["status"], unique=False)
        batch_op.create_index("idx_tournaments_tenant", ["tenant_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tournaments_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "tournament_participants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("agent_name", sa.String(length=200), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tournament_participants", schema=None) as batch_op:
        batch_op.create_index(
            "idx_participant_tournament", ["tournament_id"], unique=False
        )
        batch_op.create_index("idx_participant_user", ["user_id"], unique=False)

    op.create_table(
        "tournament_rounds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tournament_rounds", schema=None) as batch_op:
        batch_op.create_index("idx_round_tournament", ["tournament_id"], unique=False)

    op.create_table(
        "tournament_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("action_data", sa.JSON(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["tournament_participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["tournament_rounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tournament_actions", schema=None) as batch_op:
        batch_op.create_index("idx_action_round", ["round_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tournament_actions", schema=None) as batch_op:
        batch_op.drop_index("idx_action_round")

    op.drop_table("tournament_actions")
    with op.batch_alter_table("tournament_rounds", schema=None) as batch_op:
        batch_op.drop_index("idx_round_tournament")

    op.drop_table("tournament_rounds")
    with op.batch_alter_table("tournament_participants", schema=None) as batch_op:
        batch_op.drop_index("idx_participant_user")
        batch_op.drop_index("idx_participant_tournament")

    op.drop_table("tournament_participants")
    with op.batch_alter_table("tournaments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tournaments_tenant_id"))
        batch_op.drop_index("idx_tournaments_tenant")
        batch_op.drop_index("idx_tournaments_status")

    op.drop_table("tournaments")
    # ### end Alembic commands ###
