"""initial schema

Revision ID: 9f1fc0c9cb9f
Revises:
Create Date: 2026-03-09 14:01:18.601103

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f1fc0c9cb9f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("agent_type", sa.String(length=50), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_agent_tenant_name"),
    )
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.create_index("idx_agent_name", ["name"], unique=False)
        batch_op.create_index("idx_agent_tenant", ["tenant_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_agents_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "benchmark_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("min_submissions_for_ranking", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["benchmark_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("benchmark_categories", schema=None) as batch_op:
        batch_op.create_index(
            "idx_benchmark_category_active", ["is_active"], unique=False
        )
        batch_op.create_index(
            "idx_benchmark_category_order", ["display_order"], unique=False
        )
        batch_op.create_index("idx_benchmark_category_slug", ["slug"], unique=False)

    op.create_table(
        "game_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("game_name", sa.String(length=255), nullable=False),
        sa.Column("game_type", sa.String(length=50), nullable=False),
        sa.Column("num_players", sa.Integer(), nullable=False),
        sa.Column("num_rounds", sa.Integer(), nullable=False),
        sa.Column("num_episodes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("players_json", sa.JSON(), nullable=True),
        sa.Column("payoff_matrix_json", sa.JSON(), nullable=True),
        sa.Column("strategy_timeline_json", sa.JSON(), nullable=True),
        sa.Column("cooperation_dynamics_json", sa.JSON(), nullable=True),
        sa.Column("episodes_json", sa.JSON(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("game_results", schema=None) as batch_op:
        batch_op.create_index("idx_game_result_created", ["created_at"], unique=False)
        batch_op.create_index("idx_game_result_name", ["game_name"], unique=False)
        batch_op.create_index("idx_game_result_status", ["status"], unique=False)
        batch_op.create_index("idx_game_result_tenant", ["tenant_id"], unique=False)
        batch_op.create_index("idx_game_result_type", ["game_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_game_results_game_name"), ["game_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_game_results_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "tournament_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("game_name", sa.String(length=255), nullable=False),
        sa.Column("tournament_type", sa.String(length=50), nullable=False),
        sa.Column("num_agents", sa.Integer(), nullable=False),
        sa.Column("episodes_per_matchup", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("standings_json", sa.JSON(), nullable=True),
        sa.Column("matchups_json", sa.JSON(), nullable=True),
        sa.Column("cross_play_matrix_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tournament_results", schema=None) as batch_op:
        batch_op.create_index("idx_tournament_created", ["created_at"], unique=False)
        batch_op.create_index("idx_tournament_game", ["game_name"], unique=False)
        batch_op.create_index("idx_tournament_name", ["name"], unique=False)
        batch_op.create_index("idx_tournament_status", ["status"], unique=False)
        batch_op.create_index("idx_tournament_tenant", ["tenant_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tournament_results_game_name"), ["game_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tournament_results_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_user_tenant_email"),
        sa.UniqueConstraint("tenant_id", "username", name="uq_user_tenant_username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("idx_user_tenant", ["tenant_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_users_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "agent_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("repository_url", sa.String(length=500), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verification_badges", sa.JSON(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("total_submissions", sa.Integer(), nullable=False),
        sa.Column("best_overall_score", sa.Float(), nullable=True),
        sa.Column("best_overall_rank", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "agent_id", name="uq_agent_profile_tenant_agent"
        ),
    )
    with op.batch_alter_table("agent_profiles", schema=None) as batch_op:
        batch_op.create_index(
            "idx_agent_profile_best_score", ["best_overall_score"], unique=False
        )
        batch_op.create_index(
            "idx_agent_profile_display_name", ["display_name"], unique=False
        )
        batch_op.create_index(
            "idx_agent_profile_is_public", ["is_public"], unique=False
        )
        batch_op.create_index(
            "idx_agent_profile_is_verified", ["is_verified"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_profiles_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "marketplace_suites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("publisher_id", sa.Integer(), nullable=False),
        sa.Column("publisher_name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("license_type", sa.String(length=50), nullable=False),
        sa.Column("license_url", sa.String(length=500), nullable=True),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("github_url", sa.String(length=500), nullable=True),
        sa.Column("github_branch", sa.String(length=100), nullable=True),
        sa.Column("github_path", sa.String(length=500), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("total_downloads", sa.Integer(), nullable=False),
        sa.Column("total_installs", sa.Integer(), nullable=False),
        sa.Column("average_rating", sa.Float(), nullable=True),
        sa.Column("total_ratings", sa.Integer(), nullable=False),
        sa.Column("latest_version", sa.String(length=20), nullable=False),
        sa.Column("latest_version_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["publisher_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("marketplace_suites", schema=None) as batch_op:
        batch_op.create_index(
            "idx_marketplace_suite_category", ["category"], unique=False
        )
        batch_op.create_index(
            "idx_marketplace_suite_downloads", ["total_downloads"], unique=False
        )
        batch_op.create_index(
            "idx_marketplace_suite_featured", ["is_featured"], unique=False
        )
        batch_op.create_index(
            "idx_marketplace_suite_published", ["is_published"], unique=False
        )
        batch_op.create_index(
            "idx_marketplace_suite_publisher", ["publisher_id"], unique=False
        )
        batch_op.create_index(
            "idx_marketplace_suite_rating", ["average_rating"], unique=False
        )
        batch_op.create_index("idx_marketplace_suite_slug", ["slug"], unique=False)
        batch_op.create_index(
            "idx_marketplace_suite_tenant", ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_suites_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_suites_is_featured"),
            ["is_featured"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_suites_is_published"),
            ["is_published"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_suites_is_verified"),
            ["is_verified"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_suites_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "suite_definitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("defaults_json", sa.JSON(), nullable=False),
        sa.Column("agents_json", sa.JSON(), nullable=False),
        sa.Column("tests_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_suite_def_tenant_name"),
    )
    with op.batch_alter_table("suite_definitions", schema=None) as batch_op:
        batch_op.create_index("idx_suite_def_name", ["name"], unique=False)
        batch_op.create_index("idx_suite_def_tenant", ["tenant_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_suite_definitions_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "suite_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("suite_name", sa.String(length=255), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("runs_per_test", sa.Integer(), nullable=False),
        sa.Column("total_tests", sa.Integer(), nullable=False),
        sa.Column("passed_tests", sa.Integer(), nullable=False),
        sa.Column("failed_tests", sa.Integer(), nullable=False),
        sa.Column("success_rate", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("suite_executions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_agent_started", ["agent_id", "started_at"], unique=False
        )
        batch_op.create_index(
            "idx_suite_agent", ["suite_name", "agent_id"], unique=False
        )
        batch_op.create_index(
            "idx_suite_started", ["suite_name", "started_at"], unique=False
        )
        batch_op.create_index("idx_suite_tenant", ["tenant_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_suite_executions_suite_name"), ["suite_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_suite_executions_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "marketplace_suite_reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("marketplace_suite_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("version_reviewed", sa.String(length=20), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("is_flagged", sa.Boolean(), nullable=False),
        sa.Column("helpful_count", sa.Integer(), nullable=False),
        sa.Column("not_helpful_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["marketplace_suite_id"],
            ["marketplace_suites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "marketplace_suite_id", "user_id", name="uq_marketplace_review_user"
        ),
    )
    with op.batch_alter_table("marketplace_suite_reviews", schema=None) as batch_op:
        batch_op.create_index(
            "idx_marketplace_review_approved", ["is_approved"], unique=False
        )
        batch_op.create_index("idx_marketplace_review_rating", ["rating"], unique=False)
        batch_op.create_index(
            "idx_marketplace_review_suite", ["marketplace_suite_id"], unique=False
        )
        batch_op.create_index("idx_marketplace_review_user", ["user_id"], unique=False)

    op.create_table(
        "marketplace_suite_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("marketplace_suite_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("version_major", sa.Integer(), nullable=False),
        sa.Column("version_minor", sa.Integer(), nullable=False),
        sa.Column("version_patch", sa.Integer(), nullable=False),
        sa.Column("changelog", sa.Text(), nullable=True),
        sa.Column("breaking_changes", sa.Boolean(), nullable=False),
        sa.Column("suite_content", sa.JSON(), nullable=False),
        sa.Column("test_count", sa.Integer(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("downloads", sa.Integer(), nullable=False),
        sa.Column("is_latest", sa.Boolean(), nullable=False),
        sa.Column("is_deprecated", sa.Boolean(), nullable=False),
        sa.Column("deprecation_message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["marketplace_suite_id"],
            ["marketplace_suites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "marketplace_suite_id", "version", name="uq_marketplace_version"
        ),
    )
    with op.batch_alter_table("marketplace_suite_versions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_marketplace_version_latest", ["is_latest"], unique=False
        )
        batch_op.create_index(
            "idx_marketplace_version_semver",
            ["version_major", "version_minor", "version_patch"],
            unique=False,
        )
        batch_op.create_index(
            "idx_marketplace_version_suite", ["marketplace_suite_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_suite_versions_is_latest"),
            ["is_latest"],
            unique=False,
        )

    op.create_table(
        "published_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("suite_execution_id", sa.Integer(), nullable=False),
        sa.Column("agent_profile_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("success_rate", sa.Float(), nullable=False),
        sa.Column("total_tests", sa.Integer(), nullable=False),
        sa.Column("passed_tests", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("total_cost_usd", sa.Float(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("verified_by_id", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_profile_id"],
            ["agent_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suite_execution_id"],
            ["suite_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "suite_execution_id", name="uq_published_result_suite_execution"
        ),
    )
    with op.batch_alter_table("published_results", schema=None) as batch_op:
        batch_op.create_index(
            "idx_published_result_category", ["category"], unique=False
        )
        batch_op.create_index(
            "idx_published_result_published_at", ["published_at"], unique=False
        )
        batch_op.create_index("idx_published_result_score", ["score"], unique=False)
        batch_op.create_index(
            "idx_published_result_verified", ["is_verified"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_published_results_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_published_results_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "test_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("suite_execution_id", sa.Integer(), nullable=False),
        sa.Column("test_id", sa.String(length=255), nullable=False),
        sa.Column("test_name", sa.String(length=255), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("total_runs", sa.Integer(), nullable=False),
        sa.Column("successful_runs", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("statistics", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["suite_execution_id"],
            ["suite_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("suite_execution_id", "test_id", name="uq_suite_test"),
    )
    with op.batch_alter_table("test_executions", schema=None) as batch_op:
        batch_op.create_index("idx_test_started", ["started_at"], unique=False)
        batch_op.create_index(
            "idx_test_suite_exec", ["suite_execution_id", "test_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_test_executions_test_id"), ["test_id"], unique=False
        )

    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("test_execution_id", sa.Integer(), nullable=False),
        sa.Column("evaluator_name", sa.String(length=100), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("total_checks", sa.Integer(), nullable=False),
        sa.Column("passed_checks", sa.Integer(), nullable=False),
        sa.Column("failed_checks", sa.Integer(), nullable=False),
        sa.Column("checks_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_execution_id"],
            ["test_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "marketplace_suite_installs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("marketplace_suite_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version_installed", sa.String(length=20), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("installed_at", sa.DateTime(), nullable=False),
        sa.Column("uninstalled_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["marketplace_suite_id"],
            ["marketplace_suites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["marketplace_suite_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("marketplace_suite_installs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_marketplace_install_active", ["is_active"], unique=False
        )
        batch_op.create_index(
            "idx_marketplace_install_suite", ["marketplace_suite_id"], unique=False
        )
        batch_op.create_index(
            "idx_marketplace_install_tenant", ["tenant_id"], unique=False
        )
        batch_op.create_index("idx_marketplace_install_user", ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_marketplace_suite_installs_tenant_id"),
            ["tenant_id"],
            unique=False,
        )

    op.create_table(
        "run_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("test_execution_id", sa.Integer(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("response_status", sa.String(length=20), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("total_steps", sa.Integer(), nullable=True),
        sa.Column("tool_calls", sa.Integer(), nullable=True),
        sa.Column("llm_calls", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column("events_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_execution_id"],
            ["test_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_execution_id", "run_number", name="uq_test_run"),
    )
    with op.batch_alter_table("run_results", schema=None) as batch_op:
        batch_op.create_index("idx_run_test_exec", ["test_execution_id"], unique=False)

    op.create_table(
        "score_components",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("test_execution_id", sa.Integer(), nullable=False),
        sa.Column("component_name", sa.String(length=50), nullable=False),
        sa.Column("raw_value", sa.Float(), nullable=True),
        sa.Column("normalized_value", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("weighted_value", sa.Float(), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_execution_id"],
            ["test_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "test_execution_id", "component_name", name="uq_test_component"
        ),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_result_id", sa.Integer(), nullable=False),
        sa.Column("artifact_type", sa.String(length=20), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("content_type", sa.String(length=256), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("data_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_result_id"],
            ["run_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artifacts")
    op.drop_table("score_components")
    with op.batch_alter_table("run_results", schema=None) as batch_op:
        batch_op.drop_index("idx_run_test_exec")

    op.drop_table("run_results")
    with op.batch_alter_table("marketplace_suite_installs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_marketplace_suite_installs_tenant_id"))
        batch_op.drop_index("idx_marketplace_install_user")
        batch_op.drop_index("idx_marketplace_install_tenant")
        batch_op.drop_index("idx_marketplace_install_suite")
        batch_op.drop_index("idx_marketplace_install_active")

    op.drop_table("marketplace_suite_installs")
    op.drop_table("evaluation_results")
    with op.batch_alter_table("test_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_executions_test_id"))
        batch_op.drop_index("idx_test_suite_exec")
        batch_op.drop_index("idx_test_started")

    op.drop_table("test_executions")
    with op.batch_alter_table("published_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_published_results_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_published_results_category"))
        batch_op.drop_index("idx_published_result_verified")
        batch_op.drop_index("idx_published_result_score")
        batch_op.drop_index("idx_published_result_published_at")
        batch_op.drop_index("idx_published_result_category")

    op.drop_table("published_results")
    with op.batch_alter_table("marketplace_suite_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_marketplace_suite_versions_is_latest"))
        batch_op.drop_index("idx_marketplace_version_suite")
        batch_op.drop_index("idx_marketplace_version_semver")
        batch_op.drop_index("idx_marketplace_version_latest")

    op.drop_table("marketplace_suite_versions")
    with op.batch_alter_table("marketplace_suite_reviews", schema=None) as batch_op:
        batch_op.drop_index("idx_marketplace_review_user")
        batch_op.drop_index("idx_marketplace_review_suite")
        batch_op.drop_index("idx_marketplace_review_rating")
        batch_op.drop_index("idx_marketplace_review_approved")

    op.drop_table("marketplace_suite_reviews")
    with op.batch_alter_table("suite_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suite_executions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_suite_executions_suite_name"))
        batch_op.drop_index("idx_suite_tenant")
        batch_op.drop_index("idx_suite_started")
        batch_op.drop_index("idx_suite_agent")
        batch_op.drop_index("idx_agent_started")

    op.drop_table("suite_executions")
    with op.batch_alter_table("suite_definitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suite_definitions_tenant_id"))
        batch_op.drop_index("idx_suite_def_tenant")
        batch_op.drop_index("idx_suite_def_name")

    op.drop_table("suite_definitions")
    with op.batch_alter_table("marketplace_suites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_marketplace_suites_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_marketplace_suites_is_verified"))
        batch_op.drop_index(batch_op.f("ix_marketplace_suites_is_published"))
        batch_op.drop_index(batch_op.f("ix_marketplace_suites_is_featured"))
        batch_op.drop_index(batch_op.f("ix_marketplace_suites_category"))
        batch_op.drop_index("idx_marketplace_suite_tenant")
        batch_op.drop_index("idx_marketplace_suite_slug")
        batch_op.drop_index("idx_marketplace_suite_rating")
        batch_op.drop_index("idx_marketplace_suite_publisher")
        batch_op.drop_index("idx_marketplace_suite_published")
        batch_op.drop_index("idx_marketplace_suite_featured")
        batch_op.drop_index("idx_marketplace_suite_downloads")
        batch_op.drop_index("idx_marketplace_suite_category")

    op.drop_table("marketplace_suites")
    with op.batch_alter_table("agent_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_profiles_tenant_id"))
        batch_op.drop_index("idx_agent_profile_is_verified")
        batch_op.drop_index("idx_agent_profile_is_public")
        batch_op.drop_index("idx_agent_profile_display_name")
        batch_op.drop_index("idx_agent_profile_best_score")

    op.drop_table("agent_profiles")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_tenant_id"))
        batch_op.drop_index("idx_user_tenant")

    op.drop_table("users")
    with op.batch_alter_table("tournament_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tournament_results_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_tournament_results_game_name"))
        batch_op.drop_index("idx_tournament_tenant")
        batch_op.drop_index("idx_tournament_status")
        batch_op.drop_index("idx_tournament_name")
        batch_op.drop_index("idx_tournament_game")
        batch_op.drop_index("idx_tournament_created")

    op.drop_table("tournament_results")
    with op.batch_alter_table("game_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_results_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_game_results_game_name"))
        batch_op.drop_index("idx_game_result_type")
        batch_op.drop_index("idx_game_result_tenant")
        batch_op.drop_index("idx_game_result_status")
        batch_op.drop_index("idx_game_result_name")
        batch_op.drop_index("idx_game_result_created")

    op.drop_table("game_results")
    with op.batch_alter_table("benchmark_categories", schema=None) as batch_op:
        batch_op.drop_index("idx_benchmark_category_slug")
        batch_op.drop_index("idx_benchmark_category_order")
        batch_op.drop_index("idx_benchmark_category_active")

    op.drop_table("benchmark_categories")
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agents_tenant_id"))
        batch_op.drop_index("idx_agent_tenant")
        batch_op.drop_index("idx_agent_name")

    op.drop_table("agents")
    # ### end Alembic commands ###
