"""initial schema

Revision ID: c25a35e0b9eb
Revises:
Create Date: 2026-03-09 14:01:23.213546

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c25a35e0b9eb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ab_experiments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("suite_name", sa.String(length=255), nullable=False),
        sa.Column("test_ids_json", sa.JSON(), nullable=True),
        sa.Column("control_variant_json", sa.JSON(), nullable=False),
        sa.Column("treatment_variant_json", sa.JSON(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("rollback_config_json", sa.JSON(), nullable=False),
        sa.Column("min_sample_size", sa.Integer(), nullable=False),
        sa.Column("max_sample_size", sa.Integer(), nullable=True),
        sa.Column("max_duration_days", sa.Integer(), nullable=True),
        sa.Column("significance_level", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("concluded_at", sa.DateTime(), nullable=True),
        sa.Column("paused_at", sa.DateTime(), nullable=True),
        sa.Column("conclusion_reason", sa.Text(), nullable=True),
        sa.Column("winner", sa.String(length=20), nullable=True),
        sa.Column("results_json", sa.JSON(), nullable=True),
        sa.Column("rollback_triggered", sa.Boolean(), nullable=False),
        sa.Column("consecutive_degradation_checks", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("ab_experiments", schema=None) as batch_op:
        batch_op.create_index(
            "idx_ab_experiment_status_created", ["status", "created_at"], unique=False
        )
        batch_op.create_index("idx_ab_experiment_suite", ["suite_name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ab_experiments_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ab_experiments_suite_name"), ["suite_name"], unique=False
        )

    op.create_table(
        "cost_budgets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("limit_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("alert_threshold", sa.Float(), nullable=False),
        sa.Column("scope_json", sa.JSON(), nullable=True),
        sa.Column("alert_channels_json", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("cost_budgets", schema=None) as batch_op:
        batch_op.create_index("idx_budget_active", ["is_active"], unique=False)
        batch_op.create_index("idx_budget_period", ["period"], unique=False)

    op.create_table(
        "cost_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("test_id", sa.String(length=255), nullable=True),
        sa.Column("suite_id", sa.String(length=255), nullable=True),
        sa.Column("agent_name", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cost_records", schema=None) as batch_op:
        batch_op.create_index(
            "idx_cost_agent_timestamp", ["agent_name", "timestamp"], unique=False
        )
        batch_op.create_index(
            "idx_cost_model_timestamp", ["model", "timestamp"], unique=False
        )
        batch_op.create_index(
            "idx_cost_provider_timestamp", ["provider", "timestamp"], unique=False
        )
        batch_op.create_index(
            "idx_cost_suite_timestamp", ["suite_id", "timestamp"], unique=False
        )
        batch_op.create_index(
            "idx_cost_test_timestamp", ["test_id", "timestamp"], unique=False
        )
        batch_op.create_index(
            "idx_cost_timestamp_provider_model",
            ["timestamp", "provider", "model"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_cost_records_agent_name"), ["agent_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cost_records_model"), ["model"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cost_records_provider"), ["provider"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cost_records_suite_id"), ["suite_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cost_records_test_id"), ["test_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cost_records_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "scheduled_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("recipients_json", sa.JSON(), nullable=True),
        sa.Column("include_trends", sa.Boolean(), nullable=False),
        sa.Column("include_anomalies", sa.Boolean(), nullable=False),
        sa.Column("include_correlations", sa.Boolean(), nullable=False),
        sa.Column("filters_json", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_run", sa.DateTime(), nullable=True),
        sa.Column("next_run", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("scheduled_reports", schema=None) as batch_op:
        batch_op.create_index(
            "idx_report_active_next_run", ["is_active", "next_run"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_reports_next_run"), ["next_run"], unique=False
        )

    op.create_table(
        "ab_experiment_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("variant_name", sa.String(length=100), nullable=False),
        sa.Column("test_id", sa.String(length=255), nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["ab_experiments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    with op.batch_alter_table("ab_experiment_observations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_ab_obs_experiment_timestamp",
            ["experiment_id", "timestamp"],
            unique=False,
        )
        batch_op.create_index(
            "idx_ab_obs_experiment_variant",
            ["experiment_id", "variant_name"],
            unique=False,
        )
        batch_op.create_index("idx_ab_obs_test", ["test_id", "timestamp"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ab_experiment_observations_experiment_id"),
            ["experiment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_ab_experiment_observations_test_id"),
            ["test_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_ab_experiment_observations_timestamp"),
            ["timestamp"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_ab_experiment_observations_variant_name"),
            ["variant_name"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ab_experiment_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ab_experiment_observations_variant_name"))
        batch_op.drop_index(batch_op.f("ix_ab_experiment_observations_timestamp"))
        batch_op.drop_index(batch_op.f("ix_ab_experiment_observations_test_id"))
        batch_op.drop_index(batch_op.f("ix_ab_experiment_observations_experiment_id"))
        batch_op.drop_index("idx_ab_obs_test")
        batch_op.drop_index("idx_ab_obs_experiment_variant")
        batch_op.drop_index("idx_ab_obs_experiment_timestamp")

    op.drop_table("ab_experiment_observations")
    with op.batch_alter_table("scheduled_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduled_reports_next_run"))
        batch_op.drop_index("idx_report_active_next_run")

    op.drop_table("scheduled_reports")
    with op.batch_alter_table("cost_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cost_records_timestamp"))
        batch_op.drop_index(batch_op.f("ix_cost_records_test_id"))
        batch_op.drop_index(batch_op.f("ix_cost_records_suite_id"))
        batch_op.drop_index(batch_op.f("ix_cost_records_provider"))
        batch_op.drop_index(batch_op.f("ix_cost_records_model"))
        batch_op.drop_index(batch_op.f("ix_cost_records_agent_name"))
        batch_op.drop_index("idx_cost_timestamp_provider_model")
        batch_op.drop_index("idx_cost_test_timestamp")
        batch_op.drop_index("idx_cost_suite_timestamp")
        batch_op.drop_index("idx_cost_provider_timestamp")
        batch_op.drop_index("idx_cost_model_timestamp")
        batch_op.drop_index("idx_cost_agent_timestamp")

    op.drop_table("cost_records")
    with op.batch_alter_table("cost_budgets", schema=None) as batch_op:
        batch_op.drop_index("idx_budget_period")
        batch_op.drop_index("idx_budget_active")

    op.drop_table("cost_budgets")
    with op.batch_alter_table("ab_experiments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ab_experiments_suite_name"))
        batch_op.drop_index(batch_op.f("ix_ab_experiments_status"))
        batch_op.drop_index("idx_ab_experiment_suite")
        batch_op.drop_index("idx_ab_experiment_status_created")

    op.drop_table("ab_experiments")
    # ### end Alembic commands ###
