# Basic GitHub Actions workflow for ATP testing
#
# This example shows how to use the ATP reusable action.
# Copy this file to .github/workflows/atp.yml in your repository.

name: ATP Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Option 1: Use the published ATP action
      # - uses: your-org/atp-platform@v1
      #   with:
      #     suite_path: tests/suite.yaml

      # Option 2: Use the local action (if ATP is in-repo)
      - name: Run ATP tests
        id: atp
        uses: ./
        with:
          suite_path: tests/suite.yaml
          adapter: cli
          threshold: "0.8"
          budget_usd: "5.00"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            ${{ steps.atp.outputs.json_path }}
            ${{ steps.atp.outputs.junit_path }}

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ${{ steps.atp.outputs.junit_path }}

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.atp.outputs.summary_markdown }}
